services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: >
      sh -c "python manage.py migrate &&
            python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 ghost.wsgi:application"

